--- 

# tasks file for starccm

- name: Create /nfs/scratch/starccm/install
  become: true
  file:
    path: "/nfs/scratch/starccm/install"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes
    
- name: download starccm binaries
  get_url: 
    url: "{{starccm_binaries}}"  
    dest: "/nfs/scratch/starccm/install"
    mode: 0770

- name: untar starccm binaries
  ansible.builtin.unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/starccm/install" 
  with_fileglob:
    - "/nfs/scratch/starccm/install/*"

- name: install starccm
  become: true 
  shell: "./{{starccm_version}}.sh -i silent -DINSTALLDIR=/nfs/scratch/starccm/install"
  args:
    chdir: "/nfs/scratch/starccm/install/{{starccm_version}}"
 
# Post Installation 

- name: make models directory
  ansible.builtin.file:
    path: "/nfs/scratch/starccm/models"
    state: directory
    recurse: yes
    owner: opc
    group: opc
    mode: '0777'

- name: download model 
  get_url: 
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/2-6pVgv_kKDp4bxkEIG1b6LPN1FcnvGL8sR-DvK0FmrkA4XHnSNIwMUW_kWwOHXp/n/hpc/b/starccm_benchmarks/o/lemans_poly_17m.amg.sim.tar"
    dest: "/nfs/scratch/starccm/models"
    mode: '0777' 

- name: untar model
  ansible.builtin.unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/starccm/models" 
  with_fileglob:
    - "/nfs/scratch/starccm/models/*"




